package exception1;

public class ExcHanArith 
{

	
	public static void demo()throws ArithmeticException
	{
		
	System.out.println("Exception occur in demo Method");
}
	public static void main(String[] args)
	{
	       
	    try {
	    	   demo();
			   System.out.println(10/0);
			      }
			 catch (Exception E)
			 {
				 System.out.println("Number Divided by zero");
				 System.out.println(10/2);
			 }
	}
	    

} 
